# experimental lcow

image:
  - Visual Studio 2019

stack: docker

configuration: Release

branches:
  only:
    - master

install:
  - dotnet --version
  - dotnet --list-sdks
  - docker info
  - dotnet restore

build_script:
  - dotnet build

test_script:
  - dotnet test

cache:
  - '%USERPROFILE%\.nuget\packages'
  - '%USERPROFILE%\.local/share/NuGet/Cache'
