trigger:
  - master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
  - script: dotnet --list-sdks
    displayName: 'List dotnet sdks'
  - script: docker info
    displayName: 'Show docker info'
  - powershell: '[Environment]::SetEnvironmentVariable("LCOW_SUPPORTED", "1", "Machine")'
    displayName: Setting LCOW environment variable
  - script: docker info
    displayName: 'Show docker info after switching to lcow'
  - powershell: Restart-Service Docker
    displayName: Restart docker
  - powershell: '& azure-install-docker-ce.ps1'
    displayName: 'Install docker ce'
  - script: docker info
    displayName: 'Show docker info after switching to lcow'
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
  - script: dotnet test --configuration $(buildConfiguration)
    displayName: 'dotnet test $(buildConfiguration)'