name: ci

on:
  pull_request:
    branches: 
      - master

jobs:
  test:
    name: Compile and run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.1.x', '6.0.x' ]
    steps:
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install sonar tool
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install dependencies
        run: dotnet restore

      - name: SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build
        run: dotnet build

      - name: Test with coverage
        run: dotnet test testcontainers-dotnet.sln /p:CollectCoverage=true /p:CoverletOutputFormat='json%2copencover' /p:CoverletOutput=../bin/coverage/ /p:MergeWith='../bin/coverage/coverage.json'

      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          files: test/bin/coverage/coverage.opencover.xml
