name: ci

on:
  push:
    tags: 
      - v[0-9].[0-9]+.[0-9]+

jobs:
  test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.x

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Publish
        run: ./remote-publish.sh ${{ secrets.NUGET_API_KEY }} https://www.nuget.org/api/v2/package
